name: Daily Indian Market AI
on:
  schedule:
    - cron: '30 2 * * *' # 02:30 UTC is 08:00 AM IST
  workflow_dispatch: # Allows manual run

jobs:
  market-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Tools
        run: pip install feedparser yfinance pandas textblob

      - name: Run AI Model
        run: python main_engine.py

      - name: Save Today Report
        uses: actions/upload-artifact@v4
        with:
          name: stock-predictions-${{ github.run_id }}
          path: reports/
